services:
  lfi:
    build:
      context: .
      dockerfile: Dockerfile_lfi
    restart: unless-stopped
    networks:
      - lfi-network
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    restart: unless-stopped
    ports:
      - "4000:80"
    networks:
      - lfi-network

networks:
  lfi-network:
    driver: bridge
